README.md
=> update in readme

README.md
=> Added gifs to readme

C++/LCM.cpp
Created the C++ folder in the root directory along with a CPP file in it
=> Added the C++ folder as stated in the issue #19

Powershell Scripts/hello-world.ps1, Powershell Scripts/star-pattern.ps1, README.md, Website/README.md
This script will draw an arrow head.
=> Adding a PowerShell Script as in #10

README.md
Removed all the extra text and symbols in readme.md file
=> Fixed readme by removing extra symbols/operators.

Python/dictionarymethods.py
I will be adding dictionary  methods. please assign this issue to me @lovishprabhakar02
=> Adding python files #35

Python/listmethods.py
I will add list methods in python. Please assign @lovishprabhakar02 
THANKYOU
=> Adding list methods by KRITIK

HTML_form.html
@lovishprabhakar02 pls accept my pull request.
=> adding html file as mentioned in issue #62

Python/generatorforfibonacci.py, Python/generatorobjexample.py, Python/generatorobjfn.py
=> Inserted new codes of python with generator function and example of it with fibonacci numbers.

C++/amstrong.cpp
cpp program to check if a number is amstrong or not #19
=> added amstrong.cpp file

Python/barplotraceusingfuncfn.py, Python/usingfuncanimationfnanimation.py, Python/usingpausefnanimation.py
added please check it if there any mistake in please notify me !
=> adding new animation function  codes in python

C++/wel.cpp
Added a cpp program that prints "Welcome".
=> Adding a cpp program as stated in #19

C++/tic_tac_toe.cpp, C++/vowels.cpp
=> adding cpp file which counts vowels in string 

Python/python_practice.py
=> I want to add a file

Java/PalindromeString.java
This is pull request for merging java file added by me.
=> I have commited a java file

Java/MergeSymmetric.java
i have committed a program to check the symmetry of a matrix in the pre-existing java programs folder.
=> added a matrix program to the folder #112

Python/string functions.py
=> My Contribution for Github Programme

Java/Primeornot.java
I added to program to perfectly check whether a number is prime or not
=> added a program to check whether a number is prime or not

HTML/session.html
=> adding changes for the session 

Python/play.py
it was not working properly on my desktop but might work on others 
but yes might i have done something wrong but i will edit it further
=> pip module to play sound

C++/circular_queues.cpp
=> adding circular queue

Python/play.py, Python/text to speech.py
=> code for text to speech

Python/Data Structures/linked_list.py, Python/Data Structures/queue.py, Python/Data Structures/stack.py
Added data structures using Python.
I am just testing the pull requests, will add more DS and A soon.
=> Data Structures using Python

Java/TowerOfHanoi.java
Adding a java program for the famous tower of hanoi problem.
=> This is a solution to the famous Tower of hanoi problem.

C++/ContactManagement.cpp
adding contact management file #19
=> adding contact management file

C++/maps.cpp
=> adding map file

Java/Hello.java
=> adding java files  from starting

Java/Literals.java
=> adding literal file

Competitive Prog/N_Queen_problem_backtracking.cpp
A competitive programming important question. My approach for the same : 
The idea is to place queens one by one in different columns, starting from the leftmost column. When we place a queen in a column, we check for clashes with already placed queens. In the current column, if we find a row for which there is no clash, we mark this row and column as part of the solution. If we do not find such a row due to clashes then we backtrack and return false.
=> N Queen Backtracking

Java/AssociativityAndPrecedency.java, Java/Ex1.java, Java/Ex2.java, Java/Ex3.java, Java/Ex4.java, Java/Ex5.java, Java/Ex6.java, Java/Ex7.java, Java/Ex8.java, Java/IncrementAndDecrementOperator.java, Java/Operator.java, Java/UserInput.java, Java/VariablesAndDatatypes.java
=> adding file on how to take input from user

Java/Ex10.java, Java/Ex11.java, Java/Ex12.java, Java/Ex13.java, Java/Ex9.java, Java/StringMethods.java, Java/Strings.java
=> adding string methods

Java/Arrays.java, Java/Conditions.java, Java/ContinueAndBreak.java, Java/DoWhileLoop.java, Java/Ex14.java, Java/Ex15.java, Java/Ex16.java, Java/Ex17.java, Java/Ex18.java, Java/Factorial.java, Java/ForEachLoop.java, Java/ForLoop.java, Java/LeftRightAngleTrianglePattern.java, Java/MultidimensionalArrays.java, Java/PrimeNumber.java, Java/ReverseTable.java, Java/SumOfEvenNumbers.java, Java/SumOfMultiplesInTable.java, Java/SwitchStatement.java, Java/Table.java, Java/WhileLoop.java
adding if else statements switch statement and some exercises
=> adding if else statements switch statement and some exercises

Java/AverageMarks.java, Java/CalculateSumOfArray.java, Java/FindIfArrayIsSorted.java, Java/FindNumberInArray.java, Java/MaxElementInArray.java, Java/Methods.java, Java/MinElementInArray.java, Java/PrimeNumber.java, Java/ReverseArray.java, Java/SumOfTwoMatrices.java
=> adding methods

Python/pattern1.py, Python/pattern2.py, Python/pattern3.py, Python/pattern4.py, Python/pattern5.py, Python/pattern6.py
patterns drawing with help of python
=> adding patterns

C++/openApplication.cpp
@lovish-prabhakar  add my c++ file which gets input from the user and open a program according to it
=> Adding a openApplication program to open o application #19

Javascript/shapes.html
Thank you for giving me the green light. I based my code off of the previous functions and have tested the answers for accuracy.
=> added in the area of circles spheres and cubes functions

Python/PrimeNumberChecker.py
I added a file to the python directory. It's a python file that checks a number to see if it is a prime number.
=> Added PrimeNumberChecker.py

Competitive Prog/No.of_inversions_in_an_array.c
I have added No.of_inversions_in_an_array.c file
=> Solves issue #204

Java/Main.java
I have successfully created and added a Java program that adds two integer numbers to the repo.
=> Adding Java program that adds two integer numbers

Know Your Code/C Langauge/.vscode/c_cpp_properties.json, Know Your Code/C Langauge/.vscode/launch.json, Know Your Code/C Langauge/.vscode/settings.json, Know Your Code/C Langauge/Linear_Search.c
=> Adding C files

Know Your Code/web_projects/LinkY/README.md
Changed image and gif link in readme, Last one was broken :\
=> Changed image and gif link in readme. #233 (closed issue)

Know Your Code/web_projects/Neon-Navbar/README.md, Know Your Code/web_projects/Neon-Navbar/index.html, Know Your Code/web_projects/Neon-Navbar/style.css
neon/glowing navbar, Glows when hovering on it
=> New project under Web_projects. Neon-Navbar #233

Know Your Code/C Langauge/inheritance.CPP, Know Your Code/C Langauge/inheritancereadme.md.txt
explaining inheritance program by using c++ ,please verify and merge if it is correct .
=> explaining inheritance by using c++ program

MLSA Event-101/HTML/ShivaniCode.html, MLSA Event-101/HTML/ShivaniCodes.html
=> Adding Changes for Program

Know Your Code/JavaScript Popup Box/README.md, Know Your Code/JavaScript Popup Box/index.html
=> Adding JavaScript files

Know Your Code/Some concept of C++/Basic of OOPS in C++.txt, Know Your Code/Some concept of C++/Date and Month.txt
=> ADDING C++ Program File

JavaScript/BMI Calculator/index.html, JavaScript/BMI Calculator/style.css
Created a new project (BMI Calculator) in JS
=> Created new JavaScript Project

JavaScript/Random Password Generator/index.html, JavaScript/Random Password Generator/style.css
Created a new project (Random Password Generator) and added it to the JavaScript directory present in know-your-code branch.
=> Created a new project (Random Password Generator)

Know Your Code/Python/Rajanya-contribute/main.py
Adding Rajanya-contribute in python which contains the main.py file which helps to identify the Palindrome strings
=> Adding Rajanya-contribute in python

Know Your Code/C++/Quadratic root finder/NEW.cpp
Adding 1 file in c++ folder for quadratic roots finder
=> Adding 1 file

Know Your Code/C++/Merge Sort/mergeSort.cpp
i have added an merge sort program written in c++ language in the know your code>c++>MergeSort
=> Merge Sort in C++

Know Your Code/C++/binarySearch/binarysearch_array.cpp
I have written fully optimise, binarySearch code in CPP.
=> Binary Search Algo

Know Your Code/C++/2d array/2darray.cpp
I have added an C++ program file in which there is a program that is  making an 2d array.  in the Know Your Code folder under c++ folder.
=> I have added an C++ program file of an 2d array

Know Your Code/C++/C++ Templates/Templates in c++.cpp, Know Your Code/C++/Exception handling in c++/Exception Handling in c++.cpp
Added two new c++ files
(1) Exception handling in C++
(2) Templates in C++
=> Adding new C++ files 

Know Your Code/C++/pointers/Pointers.cpp
=> C++ Pointers

Know Your Code/Python/Password Generator/passwordGenerator.py, Know Your Code/Python/Password Generator/readme.md
I created a python program that generates a random password that is 8 in length and contains 2 uppercase letters, 2 lowercase letters, 2 numbers and 2 symbols and added the folder to Know Your Code/Python. Refer to issue #390
=> I created a python program that generates random password

Know Your Code/Java/Bubble-sort/BubbleSort.java, Know Your Code/Java/Bubble-sort/README.md
Just a simple java program to reordenate the elements of an array using bubble sort. Implementation foreseen in issue #394
=> Adding a java program using the bubble sort algorithm.

Know Your Code/Python/hello world program/hello.py
Added a hello world program in python in the know your code folder
=> Adding hello world program

Know Your Code/Java/LongestSubstringWithoutRepeatingCharacter/LongestSubstring.Java, Know Your Code/Java/LongestSubstringWithoutRepeatingCharacter/README.md
Added program to find length of longest substring without repeating character for a string in java.
=> 404-longest-substring-java-first-contribution

Know Your Code/Java/add-diff/multiply-of-variables.java
I added a multiply file in the java section
=> added a multiply file in the java

Know Your Code/Python/Number Guessing/README.md, Know Your Code/Python/Number Guessing/number_guessing.py
=> Adding python number guessing game #407

Know Your Code/Java/Merge_Sort/MergeSort.java, Know Your Code/Java/Merge_Sort/README.md
Issue #410
Added the java code for the Merge and Sort algorithm (MergeSort.java).
Added a README.md file describing the algorithm.
=> Added MergeSort.java code and README.md

Know Your Code/Python/countdown_timer/Readme.md, Know Your Code/Python/countdown_timer/countdown_timer.py
I have added a python code for countdown timer for issue #417
=> python code of countdown timer

Know Your Code/Python/british-airways-reviews-scraping/.ipynb_checkpoints/british-aiways-scrape-checkpoint.ipynb, Know Your Code/Python/british-airways-reviews-scraping/Readme.md, Know Your Code/Python/british-airways-reviews-scraping/british-aiways-scrape.ipynb
=> PR for adding python code to scrape reviews in know-your-code branch

Know Your Code/Python/remove_duplicates_in_sorted_array/remove_duplicates.py
I am adding a Python program that removes some duplicates (in-place) such that each unique element appears at most twice. it will return the length of the altered array
=> add new python program

.idea/.gitignore, .idea/misc.xml, .idea/modules.xml, .idea/open-source-contribution-for-beginners.iml, .idea/vcs.xml, Know Your Code/Java/LinkedList/find-middle-element.java, Know Your Code/Java/LinkedList/readme.md
I made a java function, when given a head, that returns the middle Element of a LinkedList. Refer to issue #421
=> find middle element of LinkedList

Know Your Code/C++/Radix Sort
An efficient method of sorting
=> Create Radix Sort

MLSA Event-101/C++/theory/Binary_Search_Tree.cpp
I added Binary Search Tree operations here
=> I added Binary Search Tree operation performed
